# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Mao's blog
subtitle: ''
description: ''
keywords:
author: Mao
language: zh-TW
timezone: ''

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: http://example.com
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: fluid

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: git
  repo: git@github.com:JohnsonMao/JohnsonMao.github.io.git
  branch: gh-pages

# custom style
navbar:
  blog_title: "毛毛的部落格"

dark_mode:
  enable: true
  default: dark

index:
  slogan:
    enable: true
    text: 每天都要比昨天的自己更厲害！
  banner_img: "https://i.imgur.com/uKkSpVl.jpg"

post:
  comments:
    enable: true
    type: disqus
  copyright:
    enable: false

disqus:
  shortname: fluid

code:
  copy_btn: true
  highlight:
    enable: true
    line_number: true
    lib: "highlightjs"
    highlightjs:
      style: 'Github Gist'
      bg_color: false
    prismjs:
      style: "default"
      preprocess: true

about:
  avatar: https://avatars.githubusercontent.com/u/86179381?s=400&u=7d00d31b21bdf6101c6c5b4fcefd72e03951b126&v=4
  name: "毛毛"
  intro: "一個嘗試轉行的廚師"
  icons:
    - { class: 'iconfont icon-github-fill', link: 'https://github.com/JohnsonMao', tip: 'GitHub' }
    - { class: 'iconfont icon-instagram-fill', link: 'https://www.instagram.com/maomao.owo/', tip: 'Instagram' }
    - { class: 'iconfont icon-codepen-fill', link: 'https://codepen.io/vsfvjiuv-the-typescripter', tip: 'Codepen' }
    - { class: 'iconfont icon-mail', link: 'tutelary.maomao@gmail.com', tip: 'Gmail' }
    - { class: 'iconfont icon-note', link: 'https://hackmd.io/@JohnsonMao/Front-end/', tip: 'HackMD' }

footer:
  content: '<span>© 2021 <a href="/about">Johnson Mao</a> 毛毛的部落格 | 記錄成長的過程</span>
            <span> - 本站使用 
            <a href="https://hexo.io" target="_blank" rel="nofollow noopener">Hexo</a>
            &
            <a href="https://github.com/fluid-dev/hexo-theme-fluid" target="_blank" rel="nofollow noopener">Fluid 主題</a>'
  statistics:
    enable: true
    source: "busuanzi"
    pv_format: "總訪問量 {} 次"
    uv_format: "總訪客數 {} 人"



web_analytics:
  enable: true