name: Cleanup Branch Resource

permissions:
  actions: write
  contents: read

on:
  pull_request:
    types:
      - closed
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
      - name: 🛎️ Checkout
        uses: actions/checkout@v3

      - name: 🗑️ Cleanup cache
        run: |
          gh extension install actions/gh-actions-cache

          REPO=${{ github.repository }}
          BRANCH=refs/pull/${{ github.event.pull_request.number }}/merge

          echo "Fetching list of cache key"
          cacheKeysForPR=$(gh actions-cache list -R $REPO -B $BRANCH | cut -f 1 )
          echo "Cache keys for PR: $cacheKeysForPR"

          ## Setting this to not fail the workflow while deleting cache keys.
          set +e
          echo "Deleting caches..."
          for cacheKey in $cacheKeysForPR
          do
            echo "- ${cacheKey}"
            gh actions-cache delete $cacheKey -R $REPO -B $BRANCH --confirm
          done
          echo "Done"
        env:
          GH_TOKEN: ${{ github.token }}

      - name: ⚰️ Delete artifacts
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          artifacts=$(gh api /repos/${{ github.repository }}/actions/artifacts --paginate)

          for artifact in $(echo "$artifacts" | jq -r ".artifacts[] | select(.name | startswith(\"PR-$PR_NUMBER-\")) | .id"); do
            echo "filtered artifact: $artifact"
            gh api -X DELETE /repos/${{ github.repository }}/actions/artifacts/$artifact
          done
        env:
          GH_TOKEN: ${{ github.token }}
